name: test
on:
  pull_request:
    branches:
      - master
jobs:
  test-grpc:
    name: grpc-api unit test
    needs: build-android-client
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          go get -v -t -d ./...
      - name: Make test
        run: |
             make test
  build-android-aar:
    name: android aar build
    runs-on: ubuntu-latest
    container:
      image: textile/builder:1.13.1
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: '3.11.2'
      - name: install golang
        run: |
             wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
             sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
             mkdir -p $GOPATH/bin
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          go get -v -t -d ./...
      - name: install tools
        run: |
             sdkmanager --licenses
             echo y | sdkmanager "build-tools;28.0.3"
             echo y | sdkmanager "platforms;android-28"
             sdkmanager 'ndk-bundle'
      - name: check paths
        run: |
             echo $GOROOT
             echo $GOPATH
      - name: build android framework
        run: |
             export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
             go mod vendor
             mkdir -p ~/go/src/github.com/textileio
             cd ~ && mv project go/src/github.com/textileio/grpc-ipfs-lite
             cd ~/go/src/github.com/textileio/grpc-ipfs-lite
             export GO111MODULE=off
             go get golang.org/x/mobile/cmd/...
             COMMIT=$(echo $CIRCLE_SHA1 | cut -c -7)
             SUMMARY=$CIRCLE_SHA1
             if [ "${CIRCLE_TAG}" != "" ]; then
                 SUMMARY=${CIRCLE_TAG}
             fi
             DATE=$(date --iso-8601=seconds)
             FLAGS="-X github.com/textileio/grpc-ipfs-lite/common.GitSummary=${SUMMARY} -X github.com/textileio/grpc-ipfs-lite/common.BuildDate=${DATE} -X github.com/textileio/grpc-ipfs-lite/common.GitCommit=${COMMIT} -X github.com/textileio/grpc-ipfs-lite/common.GitBranch=${CIRCLE_BRANCH} -X github.com/textileio/grpc-ipfs-lite/common.GitState=clean"
             gomobile bind -v -ldflags="-w $FLAGS" -target=android -o=mobile.aar github.com/textileio/grpc-ipfs-lite/mobile
  build-android-client:
    name: android client build
    needs: build-android-aar
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: '3.11.2'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Configure Gradle
        run: |
             cd clients/android
             ./gradlew help
      - name: Check
        run: |
             cd clients/android
             ./gradlew check --stacktrace
      - name: Build
        run: |
             cd clients/android
             sed -i.bak "s/<version>/0.0.1-rc0/g" ipfslite/build.gradle
             ./gradlew ipfslite:install
